apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karumala-com-tls
spec:
  secretName: karumala-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: karumala.com
  dnsNames:
    - karumala.com
    - www.karumala.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - karumala.com
          - www.karumala.com
